### ISSUE TITLE
App failing when trying to authenticate OneDrive

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-sdk-ios#28] opened 2015-09-28 03:48 UTC
My app keeps crashing and this is the stack strace:

ODServiceInfoProvider getServiceInfoWithViewController:appConfiguration:completion:], /XcodeProjects/Project/Pods/OneDriveSDK/OneDriveSDK/Accounts/ODServiceInfoProvider.m:45
2015-09-27 23:44:19.584 PhotoCal[8800:2364421] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: viewController'

Can somebody tell me what is going wrong?

**Comment by aclev** [comment] 2015-09-28 16:51
Hi @manikkalra Can you provide a little more detail about your project?  This Assert is making sure we have a root view controller to present on.  If we cannot find one (one wasn't provided or we don't have access to the root view controller of the application) it will assert here.  Are you using the SDK in an extension or watch kit by any chance?

**Comment by ghost** [comment] 2015-09-28 16:56
Thank you for your reply! I'm presenting a 'settings' view controller modally from my root view controller. And that 'settings' controller has the option to enable OneDrive. would that be causing the issue?

**Comment by aclev** [comment] 2015-09-28 17:12
When are you setting your appid and scopes?  In your app delegate?

**Comment by ghost** [comment] 2015-09-28 17:13
Yes, that's happening in my app delegate. 
[ODClient setMicrosoftAccountAppId:@"appid" scopes:@[@"onedrive.appfolder"]];

**Comment by aclev** [comment] 2015-09-28 17:16
Are you explicitly setting the root view controller of the application after the call to set the appIds?

**Comment by ghost** [comment] 2015-09-28 17:18
Yes, I was doing something like that:

  [rootviewController.alloc init]...
  [ODClient setMicrosoftAccountAppId:@"appid" scopes:@[@"onedrive.appfolder"]];
    [self.window setRootViewController:rootViewController];
    [self.window makeKeyAndVisible];

**Comment by aclev** [comment] 2015-09-28 17:19
Ok, for now make that OneDrive call after you set the window.  I will work on a proper fix for this and it will be in the next release (along with your other reported issues).

**Comment by ghost** [comment] 2015-09-28 17:21
Yes, that worked for me! Thank you so much for your help :) 

One last questions, since I have the scope set to be 'onedrive.appfolder'. Will OneDrive create a folder for my app automatically and upload to it, or will I have to do it manually using the API?

**Comment by aclev** [comment] 2015-09-28 17:23
Thanks for reporting the bug! 
And yes, OneDrive will automatically create the app folder for you.

**Comment by ghost** [comment] 2015-09-28 18:25
So, I am able to present the login viewcontroller now. However, when I input my email and press 'Next', it simply shows me a blank screen and the console prints this:
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

Can you help me with this please?

Edit: I have disabled ATFS entirely for now

**Comment by aclev** [comment] 2015-09-28 18:27
Yes, this is a different problem.  Apple has a new ATS standard in iOS 9, theres some info in the [README](https://github.com/OneDrive/onedrive-sdk-ios#note-ios-9-app-transport-security-ats) about it.  With instructions on how to disable it just for the one login page you need.  Note that this is a temporary fix.

**Comment by ghost** [comment] 2015-09-28 20:21
Okay that worked, however, I keep running into issues haha
- (ODItemRequestBuilder *)item:(NSString *)item
  {
  return [[ODItemRequestBuilder alloc] initWithURL:[self.requestURL URLByAppendingPathComponent:item] 
                                                 client:self.client];
  }

This method causes the app to crash as 'item' is always nil

This maybe because I'm trying to upload an image onto OneDrive using NSData. Here is what I do:

 ODItem *imageFile = [[ODItem alloc] init];
 imageFile.name = filename;
ODItemContentRequest *request = [[[self.odClient drive] items:imageFile.id] contentRequest];

This crashes the app. Is this a valid way of uploading content?

**Comment by aclev** [comment] 2015-09-28 20:25
What are request are you trying to make?  Try taking a look at the [overview](https://github.com/OneDrive/onedrive-sdk-ios/blob/master/docs/overview.md) page for a little introduction to the SDK.

**Comment by ghost** [comment] 2015-09-28 20:27
Trying to make an upload request. This is my code:

[ODClient clientWithCompletion:^(ODClient *client, NSError *error){

```
    if (!error)
    {
        self.odClient = client;

        NSData * jpegData = UIImageJPEGRepresentation(image, 0.7);
        NSString *date = [self.formatter stringFromDate:[NSDate date]];
        NSString *filename = [NSString stringWithFormat:@"%@.jpg", date];

        ODItem *imageFile = [[ODItem alloc] init];
        imageFile.name = filename;

        ODItemContentRequest *request = [[[self.odClient drive] items:imageFile.id] contentRequest];
        ODURLSessionUploadTask *task = [request uploadFromData:jpegData completion:^(ODItem *item, NSError *error) {

            if (error)
                err(error);
            else
            { 
                     ......
            }
```

**Comment by aclev** [comment] 2015-09-28 20:39
Item is always nil because you are passing in `imageFile.id` That property has not been set yet, you have only set the name of the file.  Item Ids are generated by the service and are unique.  You can use them once the item has been created but you cannot set them or tell the service what you want them to be.  It seems like you want to upload a new image.  The easiest way to do that is to call something like this:

```
ODItemContentRequest *request = [[[self drive] itemByPath:@"path/to/file"] contentRequest];
```

However, you only have the app folder scope so you don't have write access to the root of the users one drive.  If you take a look the [App Folder](https://dev.onedrive.com/misc/appfolder.htm) documentation you can see how to address the app folders.  
Heres: an example of what you might want:

```
ODItemContentRequest *request = [[[[self.odClient drive] special:@"approot"] itemByPath:filename] contentRequest];
```

**Comment by ghost** [comment] 2015-09-28 20:59
Ah I see, I am trying that, however I keep running into this issue: 

OneDrive SDK ERROR : Failed load to load fac2d9415d8cc5f6447258697c68e7b2 as current account

My app does not crash, but cannot seem to upload the image to the OneDrive account

**Comment by aclev** [comment] 2015-09-28 21:05
Above `[ODClient clientWIthCompletion...` can you call `[ODClient setLogLevel:ODLogVerbose]` and try again? This should produce some more information with the error.

**Comment by ghost** [comment] 2015-09-28 21:07
It says: No known class method for selector 'setLogLevel:'

I can put it inside the block however:

[ODClient clientWithCompletion:^(ODClient *client, NSError *error) {

```
    [client setLogLevel:ODLogVerbose];
```

.......

**Comment by aclev** [comment] 2015-09-28 21:09
Whoops, my fault try `[ODAppConfiguration defaultConfiguration].logger setLogLevel:ODLogVerbose]`

**Comment by ghost** [comment] 2015-09-28 21:12
Here's the log:

OneDrive SDK VERBOSE : Read account : fac2d9415d8cc5f6447258697c68e7b2 from accountStore
2015-09-28 17:11:46.406 PhotoCal[11311:2605168] ADALiOS: ERROR: Error raised: 11. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:Cannot read the items in the keychain. Error code: -34018. Query: {
    acct = ZmFjMmQ5NDE1ZDhjYzVmNjQ0NzI1ODY5N2M2OGU3YjI;
    svce = "MSOpenTech.ADAL.1|aHR0cHM6Ly9sb2dpbi5saXZlLmNvbS9vYXV0aDIwX2F1dGhvcml6ZS5zcmY|aHR0cHM6Ly9hcGkub25lZHJpdmUuY29tL3YxLjA|MDAwMDAwMDA0NDE2NGEzYw";
}. ErrorCode: 11.
2015-09-28 17:11:46.407 AppName[11311:2605168] OneDrive SDK WARNING : Failed to read session fac2d9415d8cc5f6447258697c68e7b2 from keychain
2015-09-28 17:11:46.407 AppName[11311:2605168] OneDrive SDK VERBOSE : Loading fac2d9415d8cc5f6447258697c68e7b2 as current account
2015-09-28 17:11:46.407 AppName[11311:2605168] OneDrive SDK ERROR : Failed load to load fac2d9415d8cc5f6447258697c68e7b2 as current account
2015-09-28 17:11:46.408 AppName[11311:2605168] OneDrive SDK DEBUG :  ServiceInfo provider starting discovery service with URL:

**Comment by aclev** [comment] 2015-09-28 21:23
It looks like ADAL is having issues reading from your keychain and upon further investigation it actually looks like an Apple Keychain bug! Heres a [reference](https://forums.developer.apple.com/thread/4743) 
It looks like it is caused by accessing the keychain to soon after the app has launched, where/when do you call the clientWIthCompletion method?

**Comment by ghost** [comment] 2015-09-28 21:27
Huh, not sure what to do about that. After some messing around, it seems to work but I get this error:

clientWithCompletion is called when I actually try to upload a picture, or enable OneDrive in my settings viewcontroller. Neither should happen immediately after my app launching. 

2015-09-28 17:24:39.116 AppName[11422:2612038] OneDrive SDK ERROR : Error from download response Error Domain=com.microsoft.onedrive.errors Code=400 "bad request" UserInfo={error= invalidRequest : One or more invalid characters are present in the path (/Jump/App_1142311484/09-28-15|17.24.37.jpg)., NSLocalizedDescription=bad request}
2015-09-28 17:24:39.116 AppName[11422:2612038] OneDrive SDK DEBUG :  Error from response : <NSHTTPURLResponse: 0x125d83320> { URL: https://api.onedrive.com/v1.0/drive/special/approot:/09-28-15%7C17.24.37.jpg:/content } { status code: 400, headers {
    "Content-Encoding" = gzip;
    "Content-Length" = 175;
    "Content-Type" = "application/json";
    Date = "Mon, 28 Sep 2015 21:24:39 GMT";
    P3P = "CP=\"BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo\"";
    Server = "Microsoft-IIS/8.5 Microsoft-HTTPAPI/2.0";
    "Strict-Transport-Security" = "max-age=31536000; includeSubDomains";
    Via = "1.1 DM2302____PAP010 (wls-colorado)";
    "X-AsmVersion" = "UNKNOWN; 19.27.0.0";
    "X-MSNSERVER" = "BN1301____PAP185";
    "X-QosStats" = "{\"ApiId\":0,\"ResultType\":2,\"SourcePropertyId\":0,\"TargetPropertyId\":42}";
    "X-ThrowSite" = "4caa.9906";
    "X-WLSPROXY" = "DM2302____PAP010";
} }

**Comment by aclev** [comment] 2015-09-28 21:40
OneDrive reserves a few characters for internal use, you can read more about it [here](https://dev.onedrive.com/misc/path-encoding.htm) Your filenames have the "|" character in them.

**Comment by ghost** [comment] 2015-09-28 21:50
Okay, i think I have it working now. Only thing left is creating a sharable link that is open to the public. 

 [[[[[self.odClient drive] items:item.id] createLinkWithType:@"view"] request] executeWithCompletion:^(ODPermission *response, NSError *error) {
                            NSString *sharedLink = response.link.webUrl;
}........

I am using this. However, I cannot view the uploaded image as I am prompted for a login when I click on the link.

**Comment by aclev** [comment] 2015-09-28 22:01
Can you share the link?

**Comment by ghost** [comment] 2015-09-28 22:02
https://onedrive.live.com/redir?resid=D94384CB0DE3EA4F!133&authkey=!AM-TIwFXSTetyPU

**Comment by aclev** [comment] 2015-09-28 22:04
Is it possible you unshared the item?

**Comment by ghost** [comment] 2015-09-28 22:05
I don't think so. here is my code:

[[[[[self.odClient drive] items:item.id] createLinkWithType:@"view"] request] executeWithCompletion:^(ODPermission *response, NSError *error) {

```
                    if(error)
                    {
                        dispatch_async(dispatch_get_main_queue(), ^{
                            err(error);
                        });
                    }
                    else
                    {
                        NSString *sharedLink = response.link.webUrl;
                        dispatch_async(dispatch_get_main_queue(), ^{
                            success(sharedLink, item.id);
                        });
                    }
                }];
            }
        }];
```

**Comment by aclev** [comment] 2015-09-28 22:43
It looks like there may be bug, I have been able to reproduce it.  I'm investigating now, I'll update the thread when I have some more info. Thanks @manikkalra !

**Comment by ghost** [comment] 2015-09-28 22:53
My pleasure!

And thank you again for being so helpful with my issues. Really appreciate it :)

**Comment by aclev** [comment] 2015-09-29 00:57
We've identified the issue and are working on a fix now, it is not related to the SDK, but I will update the thread when the fix has shipped.

**Comment by ghost** [comment] 2015-10-15 23:41
Any updates on the fix? I have a project deadline in 2 weeks thats dependent on the public link working, so it would be great to have a ETA :)

**Comment by aclev** [comment] 2015-10-15 23:55
Unfortunately, I don't have an ETA yet.

**Comment by aclev** [comment] 2015-10-16 16:47
As workaround is it possible you create a Folder in the Documents directory with your apps name and use this folder to upload and share files?

**Comment by ghost** [comment] 2015-10-16 17:32
Does that mean the shared links will work in the Documents folder?

**Comment by aclev** [comment] 2015-10-16 17:34
Yes, the bug is around displaying shared links from within App Folders.

**Comment by ghost** [comment] 2015-10-21 04:33
Would that mean I need 'onedrive.readwrite' access?

**Comment by kevklam** [comment] 2016-05-16 18:46
The fix has been deployed service-side.

**Closed as completed by kevklam** 2016-05-16 18:46 UTC
Labels: service issue

**Comment by Ram-iOS** [comment] 2016-05-19 09:31
Path (/Jump/App_1209404152//Users/fluxtech_macmini1/Library/Developer/CoreSimulator/Devices/CA367710-4A87-4DA4-92BF-EC954D2EADEE/data/Containers/Bundle/Application/143FF58A-1D32-46F5-8AFC-6165FBCF63A1/iOSExplorer.app/Test.mov) contains invalid leading character., NSLocalizedDescription=bad request}

getting error while uploading video to oneDrive

**Comment by Ram-iOS** [comment] 2016-05-19 09:32
please anyone help me

**Comment by kevklam** [comment] 2016-05-19 20:08
@ReusIosDeveloper This issue has been closed, please open a new issue if you need assistance.

**Comment by hardikthakkar54** [comment] 2021-07-02 07:24
Change One Line - 

ODAppConfiguration.m File :

 _parentAuthController = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
 
 Replace this line - 
 
 _parentAuthController = [UIApplication sharedApplication].keyWindow.rootViewController;

**Comment by IshuRocks** [comment] 2022-12-16 04:33
Same issue when authenticate OneDrive

ODServiceInfoProvider getServiceInfoWithViewController:appConfiguration:completion:], /XcodeProjects/Project/Pods/OneDriveSDK/OneDriveSDK/Accounts/ODServiceInfoProvider.m:45
2015-09-27 23:44:19.584 PhotoCal[8800:2364421] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: viewController'
