### ISSUE TITLE
ODURLSessionDownloadTask not reporting progress correctly

### ISSUE THREAD

**Issue by fmaia** [OneDrive/onedrive-sdk-ios#74] opened 2016-03-11 12:10 UTC
Hi,

I've been trying to get progress info from OneDrive upload and download tasks. For the upload it is working fine. The download task however returns a NSProgress object that always reports "fractionCompleted" as 0.0. This happens even if the file is actually downloaded without errors.
Is this something known?

Thanks!

**Comment by SearchDream** [comment] 2016-03-24 03:24
I have the same issue, after diving in the SDK code, I found totalBytesExpectedToWrite always -1 in the following code(which is in ODURLSessionManager):

> - (void)URLSession:(NSURLSession *)session downloadTask:(NSURLSessionDownloadTask *)downloadTask
>                                          didWriteData:(int64_t)bytesWritten
>                                     totalBytesWritten:(int64_t)totalBytesWritten
>                             totalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite

**Comment by kevklam** [comment] 2016-04-20 22:27
Hi @fmaia  and @SearchDream, thanks for reporting this issue.

It looks like this is caused by the service sometimes returning the file contents with chunked transfer encoding, i.e. with no Content-Length header. When this occurs, totalBytesExpectedToWrite is -1 (**NSURLSessionTransferSizeUnknown**). The ideal long-term solution is for the service to always return Content-Length - I have forwarded this feedback to the service team, but can't comment on whether this can be implemented service-side in the near future.

In the scenario where Content-Length is not returned, the only way to know the actual size of the file is to get it from the ODItem metadata as retrieved in a separate request, and therefore cannot be integrated directly into the tool-generated downloadWithCompletion method.

The suggested workaround is to retrieve the ODItem first, read the .size property, and then manually set this value on downloadTask.progress.totalUnitCount. PR #87 when merged will allow this by preventing the ODNSUrlSessionTaskDelegate from overwriting the totalUnitCount with NSURLSessionTransferSizeUnknown.

**Closed as completed** 2016-04-27 22:31 UTC
Labels: bug
