### ISSUE TITLE
GET drive/items/root/children request fails with 400 "bad request" error.

### ISSUE THREAD

**Issue by rdv0011** [OneDrive/onedrive-sdk-ios#94] opened 2016-05-11 19:10 UTC
Hi.

   I have initialized the ODClient with the parameter capability:"Directory". When I try to get the child items of the root element SDK shows me the next error:
OneDrive SDK ERROR : Error from data task : Error Domain=com.microsoft.onedrive.errors Code=400 "bad request" UserInfo={error= malformed : (null), NSLocalizedDescription=bad request}
2016-05-11 20:16:41.435 App-iOS2[1279:242395] OneDrive SDK ERROR : Caused by request <NSMutableURLRequest: 0x124fdddc0> { URL: https://graph.windows.net/company.onmicrosoft.com/drive/items/root/children }
I am wondering what is incorrect in the request. Could someone help me to sort this out?

**Comment by kevklam** [comment] 2016-05-17 22:26
How are you getting this base URL: https://graph.windows.net/company.onmicrosoft.com/
Is this base URL being returned in the discovery process in ODBusinessAuthProvider? (see the completion block for [self discoverResourceWithAuthResult: completion:])

**Comment by rdv0011** [comment] 2016-05-19 21:27
The answer seems to be YES:
    "@odata.context" = "https://api.office.com/discovery/v2.0/me/$metadata#allServices";
    value =     (
                {
            "@odata.editLink" = "services('Directory@AZURE@v1.0')";
            "@odata.id" = "https://api.office.com/discovery/v2.0/me/services('Directory@AZURE@v1.0')";
            "@odata.type" = "#Microsoft.DiscoveryServices.ServiceInfo";
            capability = Directory;
            entityKey = "Directory@AZURE@v1.0";
            providerId = "72f988bf-86f1-41af-91ab-2d7cd011db47";
            providerName = Microsoft;
            serviceAccountType = 2;
            serviceApiVersion = "v1.0";
            serviceEndpointUri = "https://graph.windows.net/breezydev.onmicrosoft.com/";
            serviceId = AZURE;
            serviceName = "Microsoft Azure";
            serviceResourceId = "https://graph.windows.net/";
        }
    );

**Comment by kevklam** [comment] 2016-05-19 22:41
Thanks, I am following up on this. However can you provide a bit of context on why you are using Directory instead of MyFiles? If you are using services other than OneDrive, the [Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-ios) may be more useful to you.

**Comment by kevklam** [comment] 2016-05-19 22:52
@dmitryrybakov,
The capability parameter is plumbed through directly to the Discovery service, and is used to specify which service you want to get URLs for - by specifying 'Directory' you are requesting that the discovery service return the AAD service endpoint instead of OneDrive, causing the SDK to make requests to the wrong API. For all intents and purposes with this SDK, 'capability' should always be MyFiles.

If you need additional non-OneDrive functionality, you will probably want to use the Graph SDK as mentioned above, or else directly use ADAL to authenticate and code your own API requests without the assistance of a client library.

**Comment by rdv0011** [comment] 2016-05-20 06:20
Thank you for the response. I will check this information.

**Comment by rdv0011** [comment] 2016-05-20 06:36
If I set the capability parameter  to the value "MyFIles" or do not set it at all I am getting the following error:
Could not discover the api endpoint for the given user.  Make sure you have correctly enabled the SharePoint files permissions in Azure portal., NSLocalizedDescription=There was a problem logging you in

**Comment by rdv0011** [comment] 2016-05-23 15:32
@kevklam, Is there any update on this issue?

**Comment by kevklam** [comment] 2016-05-23 18:20
Sorry for the delay. Just to confirm, is your app registered on manage.windowsazure.com, or on apps.dev.microsoft.com? Apps registered on apps.dev.microsoft.com currently only work with the Graph SDK and not the OneDrive SDK.

**Comment by rdv0011** [comment] 2016-05-23 19:17
Hi Kevin,

  How to check it?

**Comment by kevklam** [comment] 2016-05-23 19:40
Go to manage.windowsazure.com and login with your O365 credentials, then look for the following:
<img width="900" alt="screenshot 2016-05-23 12 32 23" src="https://cloud.githubusercontent.com/assets/16890026/15482165/01e05f3c-20e3-11e6-84b6-37b1e367fbe5.png">

Once the app is added (or already exists), click on it to configure it:
<img width="1040" alt="screenshot 2016-05-23 12 37 42" src="https://cloud.githubusercontent.com/assets/16890026/15482245/7a97f962-20e3-11e6-9c48-c3dd1a25e4d2.png">

Ensure it has correct permissions:
<img width="967" alt="screenshot 2016-05-23 12 38 06" src="https://cloud.githubusercontent.com/assets/16890026/15482262/8a2c8f96-20e3-11e6-99a7-85b579b1859a.png">

**Comment by rdv0011** [comment] 2016-05-25 09:49
We have checked all steps. It seems that everything is correct. Unfortunately the authentication fails with the following error:
Code=1 "There was a problem logging you in" UserInfo={ODAuthErrorKey=Could not discover the api endpoint for the given user.  Make sure you have correctly enabled the SharePoint files permissions in Azure portal., NSLocalizedDescription=There was a problem logging you in

The reason is that SDK expects "Directory" capability instead of "MyFiles". If the "Directory" capability is set another error arises - the request is malformed. It seems that it is circling.

**Comment by kevklam** [comment] 2016-05-25 18:35
@dmitryrybakov, the correct capability is MyFiles. Just to verify, did you click 'save' at the bottom after adding the permissions? It's pretty easy to miss as it doesn't give any error/warning if you don't.
<img width="862" alt="screenshot 2016-05-25 11 29 22" src="https://cloud.githubusercontent.com/assets/16890026/15551715/1d4a313c-226c-11e6-9773-eb7b6d5b7597.png">

If that doesn't work, can you try creating a new application in active directory with the same permissions? I just created a new native application to test, and was able to both reproduce the behavior by not specifying the sharepoint online permissions, and resolve the issue by adding the permissions and saving.

Also, in the 99% case the only parameters that need to be specified are appId and redirectUrl, do you have a scenario need for specifying capability as well? It should look like the following:

``` objc
    [ODClient setActiveDirectoryAppId:@"{your-app-id}"
                          redirectURL:@"{your-redirectURL}"];
```

**Comment by rdv0011** [comment] 2016-05-26 10:55
I have double checked the permissions and also tried to create another app id, unfortunately with no success:
![azure-onedrive-1](https://cloud.githubusercontent.com/assets/4025952/15572397/0374797e-2349-11e6-90d8-21787badea4d.png)
As you suggested I am using the short for of the call:
 [ODClient setActiveDirectoryAppId:@"{your-app-id}"
                          redirectURL:@"{your-redirectURL}"];
I have grayed out the company related info because I am not sure that this thread is not public. Is there come other possible root cause of such behavior?

**Comment by rdv0011** [comment] 2016-05-26 11:39
I can send to you the credentials and app id. Is it possible to replicate this issue on your side?
If yes please provide an e-mail.

**Comment by kevklam** [comment] 2016-05-26 22:09
Thanks, you are correct - sensitive information should not be disclosed on this thread because it is public. Please send the information to:
kevinlam@microsoft.com

I will try to reproduce the issue and see what's going on.

**Comment by kevklam** [comment] 2016-05-27 21:34
@dmitryrybakov I wasn't able to use your credentials as you did not provide a redirect URL - however I think I have discovered the problem while I was trying to create a test user in my own tenant for you to try.

It turns out that this same error is returned if the _user_ is unlicensed. Go to https://portal.office.com and refer to the following screenshots as a guide for setting up a license for the test user account:

---

## <img width="454" alt="screenshot 2016-05-27 14 25 53" src="https://cloud.githubusercontent.com/assets/16890026/15621626/02d00d52-2417-11e6-8728-682bad7960e6.png">

## <img width="812" alt="screenshot 2016-05-27 14 21 35" src="https://cloud.githubusercontent.com/assets/16890026/15621657/35c17f84-2417-11e6-8d91-912775141093.png">

## <img width="1119" alt="screenshot 2016-05-27 14 21 55" src="https://cloud.githubusercontent.com/assets/16890026/15621677/652874e4-2417-11e6-9769-98b6b010c719.png">

## <img width="824" alt="screenshot 2016-05-27 14 22 34" src="https://cloud.githubusercontent.com/assets/16890026/15621693/8ccdbc34-2417-11e6-9828-6a18b6042b30.png">

## <img width="586" alt="screenshot 2016-05-27 14 22 47" src="https://cloud.githubusercontent.com/assets/16890026/15621701/aa8069ca-2417-11e6-96b3-5a6b6748270d.png">

You will need a seat license for each user that wants access to O365 services.

Also, for future convenience if you perform user creation from portal.office.com instead of from manage.windowsazure.com, you can perform the user creation and license assignment in 1 step instead of assigning the license separately.

Hope this helps,
Kevin

**Comment by rdv0011** [comment] 2016-06-06 18:53
Hi Kevin,
   The info you provided has helped a lot. Thanks. One more question which is not related to this topic: does this version of SDK support ordinary non-business accounts?

**Comment by rdv0011** [comment] 2016-06-06 19:04
By now I am getting the error for the ordinary account: The operation couldn’t be completed. (ADAuthenticationErrorDomain error 15.)

**Comment by kevklam** [comment] 2016-06-06 20:54
Hi Dmitry,
Non-business OneDrive ("onedrive for consumer") login requires a slightly different auth process.

App registration for Consumer apps must be done on apps.dev.microsoft.com - make sure to add platform "Mobile application" and check the box "Live SDK Support" at the bottom. Then call:

``` objc
[ODClient setMicrosoftAccountAppId:@"{client id}" scopes:@[@"onedrive.readwrite"]];
```

If you call both **setMicrosoftAccountAppId:** (Azure Active Directory appID) and **setActiveDirectoryAppId:** (apps.dev.microsoft.com appID) then an extra page will appear at the start of the login process directing the user to either business or personal login based on their email address.

Otherwise if you only call one of the two, it will direct the user to sign in using that method only (business or consumer).

**Comment by kevklam** [comment] 2016-06-07 20:47
Closing - please open a new issue if you need anything further.

**Closed as completed by kevklam** 2016-06-07 20:47 UTC
