### ISSUE TITLE
Login site not being localized after language change in the iOS settings

### ISSUE THREAD

**Issue by mobilekosmos** [OneDrive/onedrive-sdk-ios#93] opened 2016-05-11 11:50 UTC
It looks like the language being used on App install is cached by the SDK in some way, because if I change the system language in the iOS settings and then in my App try to login to OneDrive again the login site is shown in the first language used while installing the App. After reinstalling the app the login site is shown in the right language.

Tested on ipad3 iOS8 and ipad mini iOS9

**Comment by kevklam** [comment] 2016-05-17 22:42
Hi @tererecool,
I was unable to reproduce the issue on an iPhone 5c running 9.3.1 using the following steps:
1. Run iOsExplorer sample app configured for either Microsoft Account or ActiveDirectory login
2. Click 'Sign in' - brings up login page in English
3. Double-tap the 'home' button and switch app to Settings
4. Change language to French
5. Double-tap the 'home' button and switch back to iOsExplorer

At this point iOsExplorer has been terminated by the language change and relaunches, and when I click 'sign in' again the page loads in French as expected.

Are there any additional steps needed to reproduce the issue? Does this occur for you on the latest version of iOs?

**Comment by kevklam** [comment] 2016-05-23 21:19
Hi @tererecool, just wanted to ping on this - are you still experiencing the issue?

**Comment by mobilekosmos** [comment] 2016-05-24 05:33
Hi, we definitely have this problem, and it is on our priority list for our next release, but it will take some weeks, I will update this when we found the problem.

**Comment by kevklam** [comment] 2016-08-05 01:25
Closing this issue for now, please reopen if you are able to provide more repro information.

Thanks,
Kevin

**Closed as completed by kevklam** 2016-08-05 01:25 UTC
