### ISSUE TITLE
OneDrive for Business: first login attempt after entering wrong password fails

### ISSUE THREAD

**Issue by kreuli** [OneDrive/onedrive-sdk-ios#84] opened 2016-04-14 15:53 UTC
The following issue happens when using the OneDrive SDK for iOS (version 1.1.2) in my own iOS app but the same behaviour can be seen with the OneDrive app from the App Store (version 6.13.3):
- Start to sign in to OneDrive for Business by entering a OneDrive for Business email address.
- In the upcoming screen, enter a wrong password -> login is rejected (correct).
- Enter a wrong password again -> login is rejected again (correct).
- Enter the correct password -> login is rejected! (BUG)
- Enter the correct password again -> login is granted (correct).

So the bug is that the correct password is not accepted at the first time after entering a wrong password.

**Comment by kevklam** [comment] 2016-04-14 16:35
Hi @kreuli,
I'm unable to reproduce this issue on my end. Is it possible that there's something funny going on with the onscreen keyboard and auto capitalization or something like that? Does this issue reproduce consistently for you across multiple different accounts?

Thanks,
Kevin

**Comment by kreuli** [comment] 2016-04-15 07:30
Hello Kevin,

after some testing with different devices and accounts it seems that the issue relates to tablet devices only and OneDrive for Business accounts:
- I can reproduce the issue with iPad mini retina and with iPad Air 2, but not with iPhones.
- I can reproduce the issue with OneDrive for Business accounts (tried one E1 account and one E3 account) but not with OneDrive for Personal use accounts.

Observation: when entering a wrong password and tapping "Sign in", the text "we don't recognise this user ID or password" appears and the password field is cleared. When re-entering a wrong password and tapping "Sign in", the same message appears and the password field is cleared as well. When then entering the correct password and tapping "Sign in", the error message appears but the password field is not cleared! I can then simply tap the "Sign in" button again without having to enter the password (because it is still there in the text field) and logon works. So the problem is not related to the keyboard or captalization since the I don't change the text in the password field. The problem is more that somehow the first attempt seems to be incomplete or to fail somehow unexpected since the password field is not cleared.

Hope that helps to locate the issue,
Ulrich

**Comment by kevklam** [comment] 2016-08-05 01:23
Closing as this has been filed to the ID team's internal issue tracker.

**Closed as completed by kevklam** 2016-08-05 01:23 UTC
Labels: service issue
