### ISSUE TITLE
Build Failed On Case-Sensitive System

### ISSUE THREAD

**Issue by NightDream2016** [OneDrive/onedrive-sdk-ios#99] opened 2016-05-26 03:53 UTC
Hi ,

I use cocoapod to integrate this SDK in our app, but it seems there are some error when building it.

/%OURPROJECTPATH%/Pods/OneDriveSDK/OneDriveSDK/OneDriveCoreSDK/model/ODAsyncOperationStatus.h:24:9: 'UIKit/UiKit.h' file not found

and I just search & replaced the string '**UIKit/UiKit.h**' with '**UIKit/UIKit.h**' in all files of this SDK , there will be no error and run successfully in our project. but this modification will be reset when I update it from remote, so I can't use this SDK as a pod dependency target in my customize pod.
It seems like there is a spelling-mistake of UiKit.h from U"**I**"Kit.h, this error will lead to build failed when using case-sensitive system.

**Comment by kevklam** [comment] 2016-05-26 22:06
Thanks for reporting this. If you have a set of changes that resolves the issue, would you mind forking the repo and creating a pull request? I can probably get around to making this change sometime in the next few days, but my system is not case-sensitive so I won't be able to test if the issue is resolved for you or not.

**Comment by kevklam** [comment] 2016-05-27 20:08
Fixed with #101

**Closed as completed by kevklam** 2016-05-27 20:08 UTC
